server:
  name: "msProject_api"
  addr: "0.0.0.0:80"
zap:
  debugFileName: "/msProject/project-api/logs/debug/api-debug.log"
  infoFileName: "/msProject/project-api/logs/info/api-info.log"
  warnFileName: "/msProject/project-api/logs/error/api-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "0.0.0.0:2379"