server:
  name: "project_user"
  addr: "127.0.0.1:3457"

zap:
  debugFileName: "F:\\Go_item\\ms_project\\logs\\debug\\project-debug.log"
  infoFileName: "F:\\Go_item\\ms_project\\logs\\info\\project-info.log"
  warnFileName: "F:\\Go_item\\ms_project\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "localhost"
  port: 6376
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8881"
  name: "user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3309
  db: msproject
jwt:
#  过期时间 单位分钟
  accessExp: 60
  refreshExp: 10080
  accessSecret: dragon
  refreshSecret: dragonsss
